services:
  jaeger:
    image: jaegertracing/all-in-one:1.50
    ports:
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.80.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"

  dice-telemetry:
    build:
      context: ../service
      dockerfile: ../docker/Dockerfile
    image: dice-telemetry-app
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
      OTEL_TRACES_EXPORTER: "otlp"
    ports:
      - "8080:8080"
    depends_on:
      - otel-collector
