extensions:
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlp/jaeger:
    endpoint: "http://jaeger:4317"
    tls:
      insecure: true

  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"

  otlphttp/apm:
    endpoint: "http://apm-server:8200"
    headers:
      Content-Type: "application/x-ndjson"
      # Authorization: "Bearer ${APM_SECRET_TOKEN}"

  elasticsearch/logs:
    endpoint: "http://elasticsearch:9200"

  elasticsearch/metrics:
    endpoint: "http://elasticsearch:9200"

service:
  extensions: [ health_check ]
  telemetry:
    logs:
      level: error

  pipelines:
    traces:
      receivers:
        - otlp
      exporters:
        #- otlp/jaeger
        - zipkin
        #- otlphttp/apm
    logs:
      receivers:
        - otlp
      exporters:
        - elasticsearch/logs
    metrics:
      receivers:
        - otlp
      exporters:
        - elasticsearch/metrics
